export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACE_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const STORAGE_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGE_BUCKET_ID!;
